import = [
  "~/.config/alacritty/themes/themes/monokai_pro.toml"
]

live_config_reload = true

[cursor]
blink_interval = 600

[cursor.style]
blinking = "Always"

[colors.cursor]
cursor = "0xe5e5e5"
text = "0x1e1e1e"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
#family = ""

[scrolling]
history = 10000

[window]
dynamic_title = true
opacity = 0.85

[window.padding]
x = 6
y = 1

[keyboard]
bindings = [
{ key = "Return", mods = "Control", action = "SpawnNewInstance" },
{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
{ key = "-", mods = "Control", action = "DecreaseFontSize" },
{ key = "PageUp", action = "ScrollPageUp" },
{ key = "PageDown", action = "ScrollPageDown" },
]
